<?php

namespace Drupal\final_module\Form;

use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Class that provide table form.
 */
class TableForm extends FormBase {

  /**
   * This variable contains the Drupal service for translating text.
   *
   * @var \Drupal\Core\StringTranslation\TranslationManager
   */
  protected $t;

  /**
   * {@inheritDoc}
   */
  public static function create(ContainerInterface $container) {
    $instance = parent::create($container);
    $instance->t = $container->get('string_translation');
    return $instance;
  }

  /**
   * {@inheritDoc}
   */
  public function getFormId() {
    return 'table_form';
  }

  /**
   * {@inheritDoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state) {

    // Array with title for cells.
    $titles = [
      'Year',
      'Jan',
      'Feb',
      'Mar',
      'Q1',
      'Apr',
      'May',
      'Jun',
      'Q3',
      'Jul',
      'Aug',
      'Sep',
      'Q4',
      'Oct',
      'Nov',
      'Dec',
      'YTD',
    ];

    // Length of array.
    $length = count($titles) - 1;

    for ($i = 0; $i <= $length; $i++) {
      if ($i == 0 || $i == 4 || $i == 8 || $i == 12 || $i == 16 || $i == $length) {
        $rows[$titles[$i]] = [
          '#type' => 'number',
          '#step' => 'none',
          '#default_value' => NULL,
          '#disabled' => TRUE,
        ];
      }
      else {
        $rows[$titles[$i]] = [
          '#type' => 'number',
          '#step' => 'none',
          '#default_value' => NULL,
        ];
      }
    }
    
    // Create table.
    $form['table'] = [
      '#type' => 'table',
      '#header' => $titles,
      'rows' => $rows,
    ];

    return $form;
  }



  public function validateForm(array &$form, FormStateInterface $form_state) {
    parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  public function submitForm(array &$form, FormStateInterface $form_state) {
    // TODO: Implement submitForm() method.
  }

}
