<?php

namespace Drupal\final_module\Form;

use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Class that provide table form.
 */
class TableForm extends FormBase {

  /**
   * This variable contains the Drupal service for translating text.
   *
   * @var \Drupal\Core\StringTranslation\TranslationManager
   */
  protected $t;

  /**
   * {@inheritDoc}
   */
  public static function create(ContainerInterface $container) {
    $instance = parent::create($container);
    $instance->t = $container->get('string_translation');
    return $instance;
  }

  /**
   * {@inheritDoc}
   */
  public function getFormId() {
    return 'table_form';
  }

  /**
   * {@inheritDoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state) {

    // Array with title for cells.
    $titles = [
      'Year',
      'Jan',
      'Feb',
      'Mar',
      'Q1',
      'Apr',
      'May',
      'Jun',
      'Q3',
      'Jul',
      'Aug',
      'Sep',
      'Q4',
      'Oct',
      'Nov',
      'Dec',
      'YTD',
    ];

    // Length of array with titles. Used to build columns in tables.
    $length = count($titles) - 1;

    // Array with tables properties.
    $tables = $form_state->get('tables');
    if (empty($tables)) {

      // The position of the number is the number of the table.
      // The number in the array is the amount of rows.
      $tables = [1];
      $form_state->set('tables', $tables);
    }

    // A function call button that adds a new table.
    $form['addTable'] = [
      '#type' => 'submit',
      '#value' => $this->t('Add Table'),
      '#name' => 'addTable',
      '#submit' => [
        '::addTable',
      ],
    ];

    // A function call button that adds a new table.
    $form['send'] = [
      '#type' => 'submit',
      '#value' => $this->t('Send'),
      '#name' => 'send',
    ];

    $tab_num = count($tables) - 1;

    // Tables building loop.
    for ($num = 0; $num <= $tab_num; $num++) {

      // A function call button that adds a new row.
      $form['addYear' . $num] = [
        '#type' => 'submit',
        '#value' => $this->t('Add row'),

        // #name contains the number of tables. One is added because
        // in a different way #name on the first iteration will be NULL.
        '#name' => $num + 1,
        '#submit' => [
          '::addRow',
        ],
      ];

      // Create header of table.
      $form['table' . $num] = [
        '#type' => 'table',
        '#header' => $titles,
        '#attributes' => [
          'id' => 'table-form-' . $num,
        ],
      ];

      // Cycle for rows.
      for ($j = 0; $j < $tables[$num]; $j++) {

        // Cycle for columns.
        for ($i = 0; $i <= $length; $i++) {
          if ($i == 0) {
            $form['table' . $num][$j][$titles[$i]] = [
              '#type' => 'number',
              '#default_value' => date('Y') - $j,
              '#disabled' => TRUE,
            ];
          }
          elseif ($i == 4 || $i == 8 || $i == 12 || $i == 16 || $i == $length) {
            $form['table' . $num][$j][$titles[$i]] = [
              '#type' => 'number',
              '#default_value' => NULL,
              '#disabled' => TRUE,
            ];
          }
          else {
            $form['table' . $num][$j][$titles[$i]] = [
              '#type' => 'number',
            ];
          }
        }
      }
    }

    return $form;
  }

  /**
   * Function that add new row to the table.
   */
  public function addRow(array &$form, FormStateInterface $form_state) {

    // Getting a pressed button.
    $element = $form_state->getTriggeringElement();
    $tables = $form_state->get('tables');

    // Minus one because #name is number of table + 1.
    $tables[$element['#name'] - 1]++;
    $form_state->set('tables', $tables);
    $form_state->setRebuild();
  }

  /**
   * Function that add new row to the table.
   */
  public function addTable(array &$form, FormStateInterface $form_state) {
    $tables = $form_state->get('tables');
    $tables[] = 1;
    $form_state->set('tables', $tables);
    $form_state->setRebuild();
  }

  public function validateForm(array &$form, FormStateInterface $form_state) {
    \Drupal::messenger()->addStatus('sdfsdfsd');
    parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  public function submitForm(array &$form, FormStateInterface $form_state) {
    $values = $form_state->getValues();
  }

}
